# DOM PRORAB — MASTER KNOWLEDGE BASE
## Накопленные знания по проекту

**Версия:** v1.0 | **Дата:** 2026-06-11
**Назначение:** Живой документ. Содержит все стратегические решения, выводы и контекст, накопленные в рабочих сессиях. Загружается в новый чат вместе со специализированным промтом для любой рабочей ветки.

---

## CHANGELOG

### [v1.0] — 2026-06-11
- **Added:** Бизнес-контекст и текущее состояние
- **Added:** Архитектура стека и подрядчики
- **Added:** Стратегические программы (Каталог 2.0, e-com запуск)
- **Added:** Маркетинговые решения (NSM, принципы, сегменты, бюджеты, каналы)
- **Added:** Каталог-решения (5 слоёв, 4 списка, модель токсичности, Golden Assortment)
- **Added:** Операционные ограничения и факты бизнеса
- **Added:** Открытые вопросы и следующие сессии

---

## [1] БИЗНЕС-КОНТЕКСТ

### Кто мы
**Дом Прораба** — DIY-гипермаркет, Бишкек, Кыргызстан.
Пост-санация (банкротство в прошлом), работаем на собственном капитале — bootstrap.
Владелец и стратегический драйвер: **Ильяс** (основатель, тех. лидер).
Философия работы: **«Mozgi in, Hands out»** — Ильяс ставит направление и финальные коммиты, делегирует исполнение.

### Текущее состояние (snapshot)

| Метрика | Значение | Статус |
|---|---|---|
| Выручка | ~6М сом/мес | База |
| Валовая маржа | ~2М сом/мес (33%) | Выше рынка (норма DIY 22–28%) |
| GMROI медианный | 0.63 | Критически низкий — деньги в товаре |
| Доля B2B | ~0% | Greenfield |
| Доля онлайн | 0% | E-com запуск через 3–4 мес |
| Активных SKU | 6.543 | Без стратегического отбора |
| Локомотивов (AX+AY+BX) | 134 SKU | 2% каталога — критически мало |
| Маркетинг-команда | Ильяс + 0.5 помощника | Найм в Q1 |
| KAM | не нанят | Green-lit |

### Диагноз
Маржа хорошая. Проблема — **скорость оборачиваемости**: деньги застряли в товаре (GMROI 0.63 при норме 1.0–1.5). Каталог рос без стратегии — «продавать то, что продаётся». Следствие: перекос в сторону низкомаржинальных тяжёлых материалов, дефицит высокомаржинальных «money-makers», раздутый мёртвый хвост.

---

## [2] ТЕХНИЧЕСКИЙ СТЕК И ПОДРЯДЧИКИ

### Архитектура

```
1С:УТ 8          → ERP/WMS (подрядчик: List.kg)
Bitrix CMS       → Онлайн-витрина (подрядчик: Bitrix-подрядчик)
Bitrix24 CRM     → Заказы, лиды, CRM
BI на GCP        → Аналитика (Data Engineer)
   └── Cloud Functions (cf-facts, cf-dim, cf-inventory, cf-fx, cf-dq, cf-alert)
   └── Cloud Workflows (hourly + weekly pipeline)
   └── Looker Studio dashboards
   └── Telegram-алерты
```

### Архитектурные правила (нарушать нельзя)
- **CMS → 1С: ЗАПРЕЩЕНО.** Только CRM → 1С.
- **Slow Track:** ночная выгрузка 02:00, 5 CSV на FTP (каталог, цены, остатки)
- **Fast Track:** REST батч каждые 5 мин — только цены и остатки
- Три подрядчика работают параллельно, доработки идут 3–4 месяца

### BI-витрины (существующие)
- ABC_XYZ-анализ на каждый товар (по выручке, марже, стабильности)
- Snapshot-витрина с 40+ полями на SKU (см. Аппендикс B Фазы 0)
- Леджер — все товарные транзакции поденно
- GMROI, Lost Revenue, Frozen Capital, Toxicity-флаги

---

## [3] СТРАТЕГИЧЕСКИЕ ПРОГРАММЫ

### Программа 1: Каталог 2.0

**Цель:** GMROI 0.63 → 1.2+ за 9–12 месяцев через реструктуризацию каталога.

**Логика:** Трек L (ликвидация мёртвого) финансирует Трек E (расширение money-makers) и Трек T (тестирование новых локомотивов). Самофинансируемая программа.

**Структура:**
```
ФАЗА 0: ДИАГНОСТИКА     → Category Health Matrix + порог локомотива + карта капитала
ФАЗА 1: РЕШЕНИЯ         → 4 списка: KEEP / KILL / GROW / TEST
ФАЗА 2: ИСПОЛНЕНИЕ      → Трек L / Трек E / Трек T (параллельно)
```

**Статус:** Фаза 0 готова к старту. Файлы: `phase0_starter_prompt.md`, `phase0_appendix_a_decisions.md`, `phase0_appendix_b_data_schema.md`.

**Целевая структура каталога (target state, ~3.500–4.000 активных SKU):**

| Слой | % SKU | % выручки | % маржи | Функция |
|---|---|---|---|---|
| Локомотивы (Traffic Spearheads) | 10–15% | 45–55% | 25–35% | Трафик, оборот |
| Margin Engines | 25–30% | 20–30% | 40–50% | Прибыль |
| Category Completers | 30–35% | 15–20% | 15–25% | Полнота каталога |
| Test Pool | 10–15% | 5–10% | 5–10% | Новые локомотивы |
| Specialty / под заказ | 10–15% | <5% | <5% | Perception |

**Golden Assortment для e-com запуска:** ~1.800 SKU (не все 6.543 и не top-200).

**Фабрика локомотивов (Трек T):**
- 30–50 новых SKU в тест ежемесячно
- Тестовое окно 60–90 дней с обязательной видимостью
- Решающие правила зафиксированы заранее (scale / retry / kill)
- Цель: 134 локомотива сейчас → 350–450 через 12 месяцев
- KVI-прайсинг + Availability discipline + Entry Price Points + Видимость

**Ключевые решения по модели (подробнее в Аппендиксе A Фазы 0):**
- Токсичность = декомпозиция капитала (Working / Excess / Dead), не давность продажи
- ADT через in-stock days, не через календарные дни
- KILL → TRIM (живой перезатаренный) + KILL (мёртвый)
- Слои — BI-метки (auto-tagging), не управленческая структура
- QUARANTINE — маркировка, не удаление строк

---

### Программа 2: E-com запуск

**Цель:** Стать первым профессиональным e-com DIY в КР с работающими остатками, on-time доставкой и возвратом без вопросов.

**Готовность:** Bitrix CMS + Bitrix24 CRM + 1С API — в разработке, запуск через 3–4 мес.

**Критические зависимости до запуска:**
1. Data Governance (C1): 100% корректных SKU в hero-каталоге (~top-200 AX+AY)
2. Hero-SKU контент: 5+ фото, видео, schema, отзывы — ROI +20–40% органики, +30–80% конверсии
3. Unit-экономика онлайн-канала (CAC ceiling, breakeven AOV) — до старта performance
4. Service & Trust capabilities (SLA, возврат 14 дней, подтверждение заказа ≤30 мин)

**Позиционирование (draft):**
> Первый профессиональный e-commerce DIY в КР: материалы есть на сайте → доставка вовремя → возврат без вопросов. Для прорабов — отдельная программа.

---

## [4] МАРКЕТИНГОВЫЕ РЕШЕНИЯ

### NSM
- **Business:** True GMROI
- **Marketing:** CAC payback < 4 месяцев на cohort-уровне

### Принципы маркетинга

| # | Принцип | Смысл |
|---|---|---|
| P1 | Только каналы с attribution | Нет measurement — нет канала |
| P2 | Hero-SKU focus | 200–500 SKU в рекламе, не 6.543 |
| P3 | Trust before discount | Сначала доверие, потом промо |
| P4 | Прораб как multiplier | 1 прораб = 20–50 косвенных конверсий |

### Сегменты (требует валидации через in-store опрос)

| Сегмент | Описание | Бюджет | LTV |
|---|---|---|---|
| A: Активные прорабы | 5–15 заказов/мес | 60% | 500к–2М сом/год |
| B: DIY-ремонтники | Владельцы, ведущие ремонт | 25% | 50–200к/проект |
| C: Растущие прорабы | Хотят стать A | 10% | Growing |
| D: Случайные | Мелкий ремонт, hardware | 5% (только органика) | Низкий |

**Важно:** цифры по сегментам — эвристика, не данные. Реальная сегментация — после in-store опроса (500–1.000 ответов, дизайн опросника готов к разработке).

### Бюджет на маркетинг

| Период | % выручки | Сумма/мес | Фокус |
|---|---|---|---|
| Q1 2026 | 3–5% | 180–300к | Инфраструктура, контент-старт, KAM, 2GIS |
| Q2 2026 | 6–10% | 360–600к | Запуск e-com, старт performance |
| Q3–Q4 | 10–15% | 600–1.000к | Скалирование при подтверждённом unit-econ |
| Hard cap | 15% | — | Не превышать без подтверждённой unit-econ |

Performance НЕ запускать до: unit-экономика готова + hero SKU с контентом + attribution настроена.

### Каналы — волны запуска

**Волна 1 (Q1):** 2GIS + WhatsApp Business Catalog + Instagram + Telegram open-канал

**Волна 2 (Q2):** TikTok + Telegram PRO (закрытый, верифицированные прорабы) + Performance (Google Ads, Meta Ads)

**Волна 3 (Q3):** YouTube + Influencer pilots (3–5 проектов) + полноценная Content Factory

### Программы лояльности — две раздельные, не смешивать

**B2C «Дом Прораба Карта»:**
- Базовый: 2% скидка мгновенно + накопительный кэшбэк
- Серебро (50к сом/год): 3% + free доставка от X сом
- Золото (200к сом/год): 5% + free доставка всегда + персональный консультант
- Регистрация: phone-OTP, привязка к CRM

**B2B «Дом Прораба ПРО»:**
- Верификация обязательна: паспорт + 2 фото объектов ИЛИ рекомендации
- Профи (<100к сом/мес): 5% + Telegram PRO + спеццены
- Эксперт (100–500к сом/мес): 8% + личный KAM + приоритет доставки
- Партнёр (500к+ сом/мес): 10–12% + индивидуальные условия
- Закрытый Telegram-канал только для верифицированных

**Правило:** lite-программа лояльности = хуже чем никакой. Только нормальная или никакой.

### SEO-стратегия

**Подход:** Hybrid с локализацией. НЕ чистый rewrite Петровича/Леманна.

**Годовая квота:**
- 200–300 SEO-страниц (для intent capture, не для чтения)
- 150–200 Reels/TikTok (тупой, красивый, продающий — Reels-first подход)
- 30–50 YouTube long-form (для прорабского сегмента)
- 50–80 карусельных постов (прайс-таблицы + примеры)
- 5–10 inspirational landing страниц по архетипам ремонта

**Три архетипа ремонта в Бишкеке:**
1. Ошское барокко (золото, хрусталь, рюшечки)
2. Лофт (минимализм)
3. Современный дизайнерский

Контент локализуется под эти архетипы, не копирует московские форматы.

### Конкурентная разведка

**Процесс:** 100 топ-SKU × 4 конкурента (Кулук, Стройсервис, Орто-Сай/Дордой, +1) × еженедельно.
**ROI процесса: 400–700% в год** (price elasticity + stock-out exploitation + promo preemption + negotiating leverage).
**Стоимость:** ~15–25к сом/мес операционных затрат.
**Формат:** Excel-форма для сотрудников → Google Sheets с автосравнением.

---

## [5] ОПЕРАЦИОННЫЕ РЕШЕНИЯ

### Service & Trust capabilities (обязательны в день запуска e-com)
- Возврат без вопросов 14 дней
- Подтверждение заказа звонком ≤ 30 минут
- SLA доставки публичный на сайте
- NPS closed-loop: детракторы → call в 24ч, промоутеры → реферал-механика

### Логистика
- **Основной канал:** Yandex Delivery B2B API
- **Failover/тяжёлые грузы:** Porter-like сеть проверенных водителей, диспетчеризация через Telegram
- **Pass-through модель:** доставку оплачивает клиент, 0% нагрузки на маржу

### B2B / Прорабский канал
- Shared Cart механика (прораб собирает → клиент платит розничную → прораб получает бонус)
- **Открытый вопрос:** юридическое оформление бонусов прорабам (серая зона)
- **Технически:** требует отдельного ТЗ для Bitrix-подрядчика

### BNPL / Банковские партнёрства
- **Сейчас:** запустить простую рассрочку на чекауте (1–2 банка с готовым QR/POS-API)
- **Цель 18+ мес:** embedded e-com в mBank (3–5М активных юзеров) и Bakai (1М)
- **Правило:** embedded в банки — это опция 2027, не обязательная часть стратегии 2026. План должен быть жизнеспособен без неё.

---

## [6] РЕАЛИИ РЫНКА КЫРГЫЗСТАНА

| Канал/Факт | Значение |
|---|---|
| 2GIS | Основной discovery-канал (важнее Google Maps) |
| WhatsApp | Primary commerce channel, особенно для прорабов |
| Telegram | Community прорабов, дизайнеров, архитекторов |
| Instagram | Brand-канал среднего класса |
| TikTok | Растущий, DIY 25–35 лет |
| Cash on delivery | Критичен в первый год |
| Доверие | Низкое. Trust mechanics — не опция, необходимость |
| Прорабы | Гейткиперы 60–70% средних и крупных ремонтов |
| SEO-контент | Аудитория не читает длинные материалы. SEO-страницы работают на intent capture, не на чтение |
| Конкуренты | Кулук, Стройсервис, Дордой/Орто-Сай — офлайн-фокус, слабый онлайн. Окно для захвата e-com ниши открыто |

---

## [7] КОМАНДА — ПЛАН НАЙМА

### Q1 2026 (first wave)
- SMM / Content Manager: 1 FTE, 60–80к сом
- SEO-копирайтер: 0.5–1 FTE, 40–60к сом
- KAM (B2B): 1 FTE, 70–100к + % от оборота (green-lit)

### Q2 2026 (second wave)
- Performance Specialist в штат (80–120к) ИЛИ агентство (200–400к/мес)
- CRM / Loyalty Manager: 0.5–1 FTE, 50–70к
- Photo/Video producer: фриланс, по проектам

### Q3 2026
- Head of Marketing: 120–180к (только когда есть команда которой руководить)
- Category Manager: 70–120к (владелец программы «Каталог 2.0» после Ильяса)

---

## [8] ОТКРЫТЫЕ ВОПРОСЫ (не решены, требуют данных или сессии)

| # | Вопрос | Блокирует | Следующий шаг |
|---|---|---|---|
| OQ-01 | Реальная сегментация покупателей (B2C vs B2B vs дизайнеры vs прорабы) | Бюджет-аллокацию, KAM-приоритеты | In-store опрос (дизайн готов к разработке) |
| OQ-02 | Unit-экономика онлайн-канала (CAC ceiling, breakeven AOV, payback) | Запуск performance, бюджет | Отдельная сессия |
| OQ-03 | Юридическая схема B2B-бонусов для прорабов | Shared Cart механика | Юр. консультация |
| OQ-04 | Порог локомотива (точный) | Category Health Matrix | Фаза 0, Шаг 2 |
| OQ-05 | Реальный объём замороженного капитала | Питч мандата, Трек L | Фаза 0, Шаг 3 |
| OQ-06 | Покрытие money-maker категорий (сколько SKU реально нужно добирать) | Трек E бюджет | Category Health Matrix (Фаза 0) |
| OQ-07 | Cash runway в base-сценарии | Количество параллельных треков | Финансовая модель |
| OQ-08 | Условия мониторинга сезонных категорий (точный список) | Корректность stock_health | Шаг 6 валидации Фазы 0 |
| OQ-09 | Атрибуция поставщиков для UNKNOWN_SUPPLIER A-класса | Трек E (дозаказ локомотивов) | Ручная работа, параллельно Фазе 0 |

---

## [9] ЗАПРЕТЫ (что никогда не делаем)

Сформированы из ошибок, обсуждений и принципов работы. Применяются во всех сессиях.

| Запрет | Обоснование |
|---|---|
| Lite-программа лояльности | Хуже чем ничего: грязные данные, скидки без retention, привычка к дисконту |
| Performance Ads до unit-econ и hero SKU | Деньги в трубу: трафик конвертируется плохо без правильных страниц и экономики |
| Чистый rewrite контента Петровича/Леманна | Google Helpful Content Update + bounce rate + reputation risk |
| Объединение B2C и B2B-программ | Разная психология, экономика, механика — смешение убивает обе |
| Маркетинг-бюджет > 15% выручки | Self-funded, нет права на ошибку масштаба |
| Запуск канала без attribution | Невозможно оптимизировать и обосновать ROI |
| Выдуманные цифры без флага «эвристика» | Решения принимаются на данных, не на ощущениях |
| Удаление строк из витрины вместо маркировки | Итоги перестают биться с 1С — теряем доверие к аналитике |
| Токсичность по давности продажи | Событийная модель врёт в обе стороны (см. Аппендикс A R-01) |
| Стратегические решения без пересчёта на P&L | Всё должно иметь путь к GMROI или CAC payback |

---

## [10] ПРАВИЛА ПОДДЕРЖАНИЯ ЭТОГО ДОКУМЕНТА

**Когда апдейтить:**
- После каждой сессии, в которой принято решение, которое влияет на другие треки
- Когда получены реальные данные взамен эвристики (закрыть открытый вопрос из секции 8)
- Когда изменились бизнес-цифры (выручка, GMROI, состав команды)
- Когда завершён milestone (запуск e-com, найм KAM, окончание Фазы 0)

**Что апдейтить:**
- Поднять версию в шапке + добавить запись в CHANGELOG
- Закрытые открытые вопросы: перенести в соответствующую секцию с пометкой «Закрыто: [решение]»
- Новые решения: добавить в релевантную секцию
- Изменившиеся цифры: обновить таблицу в секции [1]

**Что НЕ хранить здесь:**
- Операционные детали (псевдокод, схемы колонок) → в аппендиксах конкретных программ
- Черновики и гипотезы в процессе → в рабочих сессиях
- Этот документ = финализированные знания, не рабочая область

---

*Конец документа. Версия v1.0*
